WITH CTE AS (
    SELECT 
        person_name,
        SUM(WEIGHT) OVER (ORDER BY TURN) AS CUMULATIVE_WEIGHT
    FROM Queue
)
SELECT person_name 
FROM CTE
WHERE CUMULATIVE_WEIGHT = (
    SELECT MAX(CUMULATIVE_WEIGHT) FROM CTE WHERE CUMULATIVE_WEIGHT <= 1000
);